@startuml ad-03-quan-ly-chu-de
!include ../../_usecase-style.puml
!include ../../_feature-layout.puml

actor "Quản trị viên" as AD

usecase "Quản lý chủ đề" as MAIN
usecase "Xem danh sách chủ đề" as UC1
usecase "Thêm mới chủ đề" as UC2
usecase "Cập nhật chủ đề" as UC3
usecase "Đăng nhập" as LOGIN

AD --> MAIN
UC1 ..> MAIN : <<extend>>
UC1 ..> LOGIN : <<include>>
UC2 ..> MAIN : <<extend>>
UC2 ..> LOGIN : <<include>>
UC3 ..> MAIN : <<extend>>
UC3 ..> LOGIN : <<include>>

UC1 -[hidden]down- UC2
UC2 -[hidden]down- UC3
AD -[hidden]right- MAIN
MAIN -[hidden]right- UC2
UC1 -[hidden]right- LOGIN
UC2 -[hidden]right- LOGIN
UC3 -[hidden]right- LOGIN

@enduml
