' Layout đẹp: mở hv-02-dang-xuat.drawio trong draw.io / diagrams.net
' PlantUML tự bố cục use case kém


@startuml hv-02-dang-xuat
!include ../../_usecase-style.puml
!include ../../_feature-layout.puml

actor "Học viên" as HV
usecase "Đăng xuất" as MAIN

HV --> MAIN

@enduml
